"""Notebook steps (auto-split)."""


def main() -> None:
    we_define_the_first_30_cycles_of_every_engine_as()
    rebuild_lstm_sequences_from_this_engine()
    notebook_step_004()
    notebook_step_005()
    notebook_step_006()
    sort_descending_by_prediction_range()
    notebook_step_008()
    look_for_units_with_meaningful_prediction_moveme()
    notebook_step_010()
    make_sure_you_re_only_looking_at_the_sensor_colu()
    select_a_few_high_value_sensors()
    load_dataset()
    notebook_step_014()
    define_attention_layer_that_returns_both_context()
    create_pca_based_sequences()
    predictive_maintenance_py()
    predictive_maintenance_py_2()
    for_a_specific_engine()
    lstm()
    notebook_step_021()
    predictive_maintenance_py_3()
    notebook_step_023()
    notebook_step_024()
    pseudo_code_for_llm_interaction()
